name: CI/CD Pipeline

on:
  push:
    branches:
        - master


jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: myapp
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $CONTAINER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin

      - name: Docker Build
        run: |
          docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest \
                       -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Docker Push
        run: |
          docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
          docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }}

      # - name: Update GitOps repository
      #   shell: bash
      #   env:
      #       GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
      #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #   run: |
      #       git config --global user.name "GitHub Actions"
      #       git config --global user.email "actions@github.com"

      #       # Clone GitOps repo using token
      #       git clone https://$GIT_TOKEN@github.com/AbdallahElaraby/Todo-List-nodejs-GitOps.git
      #       cd Todo-List-nodejs-GitOps
      #       ls -l
      #       cat deployment.yaml

      #       # Update image tag in deployment.yaml
      #       sed -i "s|image: .*|image: docker.io/${DOCKER_USERNAME}/myapp:${{ github.sha }}|g" deployment.yaml
      #       cat deployment.yaml
      #       git add deployment.yaml
      #       git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
      #       git push origin main
      # - name: Update GitOps repository
      #   shell: bash
      #   env:
      #     GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      #     git clone https://$GIT_TOKEN@github.com/AbdallahElaraby/Todo-List-nodejs-GitOps.git
      #     cd Todo-List-nodejs-GitOps
      #     ls -l

      #     echo "Before:"
      #     cat helm/todo-list/values.yaml

      #     # Update image tag in values.yaml
      #     sed -i "s|^\([[:space:]]*tag:\).*|\1 ${{ github.sha }}|g" helm/todo-list/values.yaml
      #     sed -i "s|^\([[:space:]]*repository:\).*|\1 docker.io/${DOCKER_USERNAME}/myapp|g" helm/todo-list/values.yaml
      #     sed -i "s|^\([[:space:]]*pullPolicy:\).*|\1 IfNotPresent|g" helm/todo-list/values.yaml

      #     echo "After:"
      #     cat helm/todo-list/values.yaml

      #     git add helm/todo-list/values.yaml
      #     git commit -m "Update Helm image tag to ${{ github.sha }}" || echo "No changes to commit"
      #     git push origin main


      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        run: |
          set -e  # Fail early on error

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://$GIT_TOKEN@github.com/AbdallahElaraby/Todo-List-nodejs-GitOps.git
          cd Todo-List-nodejs-GitOps
          echo "Before update:"
          cat helm/todo-list/values.yaml

          # Ensure DOCKER_USERNAME is not empty
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME is empty. Check your GitHub Secrets setup."
            exit 1
          fi

          # Update Helm values.yaml
          sed -i "s|^\([[:space:]]*repository:\).*|\1 docker.io/${DOCKER_USERNAME}/myapp|g" helm/todo-list/values.yaml
          sed -i "s|^\([[:space:]]*tag:\).*|\1 ${{ github.sha }}|g" helm/todo-list/values.yaml
          sed -i "s|^\([[:space:]]*pullPolicy:\).*|\1 IfNotPresent|g" helm/todo-list/values.yaml

          echo "After update:"
          cat helm/todo-list/values.yaml

          git add helm/todo-list/values.yaml
          git commit -m "Update Helm image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
